import type { SkillArea } from "@/lib/trainer/types";

export const areaMeta: Record<
  SkillArea,
  { label: string; target: number; module: string }
> = {
  "csharp-fundamentals": { label: "C# fundamentals", target: 5, module: "A" },
  "advanced-csharp": { label: "Advanced C#", target: 4, module: "A" },
  "oop-solid": { label: "OOP and SOLID", target: 5, module: "B" },
  "design-patterns": { label: "Design patterns", target: 4, module: "B" },
  dsa: { label: "Data structures and algorithms", target: 3, module: "A" },
  "unity-lifecycle": { label: "Unity lifecycle", target: 5, module: "D" },
  "unity-architecture": { label: "Unity architecture", target: 5, module: "C" },
  profiling: { label: "Profiling and optimization", target: 5, module: "E" },
  rendering: { label: "Rendering", target: 4, module: "F" },
  memory: { label: "Memory management", target: 4, module: "E" },
  assets: { label: "Asset management", target: 4, module: "G" },
  animation: { label: "Animation", target: 4, module: "H" },
  physics: { label: "Physics", target: 4, module: "H" },
  ui: { label: "UI architecture", target: 4, module: "I" },
  networking: { label: "Networking / collaboration", target: 4, module: "J" },
  "cross-platform": { label: "Cross-platform deployment", target: 4, module: "K" },
  testing: { label: "Testing", target: 4, module: "L" },
  debugging: { label: "Debugging", target: 5, module: "L" },
  documentation: { label: "Technical documentation", target: 4, module: "M" },
  estimation: { label: "Estimation", target: 4, module: "N" },
  leadership: { label: "Leadership", target: 4, module: "N" },
  mentoring: { label: "Mentoring", target: 4, module: "N" },
  conflict: { label: "Conflict management", target: 4, module: "N" },
  requirements: { label: "Requirement analysis", target: 4, module: "M" },
  "technical-english": { label: "Technical English", target: 4, module: "O" },
};

export const areaOrder: SkillArea[] = [
  "csharp-fundamentals",
  "advanced-csharp",
  "oop-solid",
  "design-patterns",
  "dsa",
  "unity-lifecycle",
  "unity-architecture",
  "profiling",
  "rendering",
  "memory",
  "assets",
  "animation",
  "physics",
  "ui",
  "networking",
  "cross-platform",
  "testing",
  "debugging",
  "documentation",
  "estimation",
  "leadership",
  "mentoring",
  "conflict",
  "requirements",
  "technical-english",
];
