import type { Article, Block } from "@/lib/encyclopedia/types";

function h2(id: string, text: string): Block {
  return { type: "h2", id, text };
}
function p(text: string): Block {
  return { type: "p", text };
}
function ul(items: string[]): Block {
  return { type: "ul", items };
}
function ol(items: string[]): Block {
  return { type: "ol", items };
}
function callout(tone: "tip" | "warn" | "honest" | "lead", title: string, text: string): Block {
  return { type: "callout", tone, title, text };
}
function table(headers: string[], rows: string[][]): Block {
  return { type: "table", headers, rows };
}
function qa(q: string, a: string): Block {
  return { type: "qa", q, a };
}

export const unityArticles: Article[] = [
  {
    id: "csharp",
    title: "C# for Unity leads",
    group: "engineering",
    summary:
      "Value vs reference, boxing, GC, LINQ, async lifetime, collections, and what a lead actually enforces in review.",
    readMinutes: 14,
    tags: ["C#", "GC", "boxing", "async", "LINQ"],
    related: ["lifecycle", "profiling", "unity-architecture"],
    practiceTopic: "value-ref",
    suggestedQuestions: [
      "A teammate says structs never GC. How do I correct them?",
      "Why is LINQ in Update a maybe, not an always?",
      "Coroutine vs async/await in a room download?",
    ],
    blocks: [
      h2("value-ref", "Value types, reference types, stack and heap"),
      p("A value type is copied. A reference type is a handle to one object. The stack holds short-lived frames. The heap holds GC-managed objects. That is the start, not the whole story."),
      p("Structs often live on the stack, but they also live on the heap as fields of classes, in arrays, and when boxed. Closures capture variables onto a compiler-generated heap class. “Structs never GC” is false."),
      callout("warn", "Boxing", "Boxing wraps a value type in a heap object. It appears with object, non-generic interfaces, some LINQ, and enum keys in old dictionaries. Prove it with GC Alloc before rewriting a codebase."),
      h2("linq", "LINQ in Update"),
      p("LINQ can allocate iterators, delegates, and boxed enumerators. It is not automatically the frame budget problem. Reproduce on a development player, look at GC Alloc and hitch alignment, change one hot path, remeasure on a mid-range device. Do not ban LINQ in editor tools or cold paths."),
      h2("async", "async/await, Tasks, coroutines"),
      p("After await, the MonoBehaviour may be destroyed. Production pattern: UniTask/Awaitable plus a CancellationToken cancelled in OnDisable/OnDestroy. async void is an incident except for fenced event handlers."),
      p("Coroutines remain fine for simple timed Unity sequences you want to see in the Profiler, if StopCoroutine/disable is paired. Downloads, composition, and errors usually favor awaitables."),
      ul([
        "Do not touch transforms after cancel",
        "Do not fire-and-forget Addressables.LoadAssetAsync when the user can leave the room",
        "Do not mix untracked tasks with a hidden coroutine loop",
      ]),
      h2("review-bar", "What you enforce"),
      ul([
        "No boxing in a measured hot path",
        "IDisposable for owned CTS, files, RenderTextures you created — not every MonoBehaviour",
        "Assembly definitions so UI does not compile against room internals",
        "Tests for domain rules without a Transform",
      ]),
      qa("foreach on List?", "List<T>.foreach uses a struct enumerator and is usually fine. foreach via IEnumerable can box. Prove allocation; do not start a style war."),
    ],
  },
  {
    id: "solid-patterns",
    title: "OOP, SOLID, and patterns",
    group: "engineering",
    summary: "Patterns answer variation. Unity fails SOLID with god MonoBehaviours and 12-method interactables.",
    readMinutes: 12,
    tags: ["SOLID", "patterns", "composition", "interaction"],
    related: ["unity-architecture", "networking", "animation-physics"],
    practiceTopic: "solid",
    suggestedQuestions: [
      "Design doors, machines, tools, and seats without a huge hierarchy.",
      "When is Abstract Factory the wrong tool?",
      "Where does occupancy live?",
    ],
    blocks: [
      h2("solid", "SOLID as change management"),
      table(
        ["Letter", "Unity failure"],
        [
          ["S", "God MonoBehaviour changes for input, anim, save, and net"],
          ["O", "40-case switch on interactable type"],
          ["L", "Seat.Use() throws because it inherited Door.Use()"],
          ["I", "IInteractable with 12 methods"],
          ["D", "Gameplay new()s a concrete network client"],
        ]
      ),
      h2("interaction", "Interaction without a class tree"),
      p("Small components. Segregated interfaces: IInteractable, IOccupiable, IHoldable only when needed. An interaction service resolves a target and issues a command. Occupancy and authority live outside the view so tests do not need a scene."),
      h2("patterns", "Patterns that earn their keep"),
      ul([
        "Strategy — use behaviors",
        "Command — request, undo, network",
        "Object pool — spawned tools and VFX",
        "Observer / events — with enable/disable pairing",
        "DI / composition root — VContainer or bootstrap, not Service Locator in Update",
      ]),
      callout("warn", "Overuse", "Three prefabs do not need Abstract Factory. A mediator that every hover hits is untraceable. Event bus for everything is not architecture."),
      h2("shared", "Shared objects"),
      p("Two users, one tool: server (or host) occupancy lock, deny + fail pose for the loser, timeout on pause/disconnect. Not parenting. Not a bool on the MonoBehaviour. Not dual Rigidbodies."),
    ],
  },
  {
    id: "unity-architecture",
    title: "Unity application architecture",
    group: "engineering",
    summary: "Thin MonoBehaviours, composition root, asmdefs, rooms as content packs, testability.",
    readMinutes: 12,
    tags: ["architecture", "asmdef", "bootstrap", "ScriptableObject"],
    related: ["csharp", "assets", "lifecycle"],
    practiceTopic: "boundaries",
    suggestedQuestions: [
      "What logic must not live in MonoBehaviour?",
      "How do downloaded user rooms change the structure?",
      "Where do feature flags live?",
    ],
    blocks: [
      h2("layers", "Layers"),
      p("Presentation (Unity views) → Application (use-cases) → Domain (rules) → Infrastructure (save, network, analytics). Scenes compose objects; they are not the architecture."),
      h2("mb", "MonoBehaviour as adapter"),
      p("Lifecycle, serialization, animation, physics callbacks stay on MB. Occupancy, save schema, invite permissions, scoring rules are plain C#. If a rule needs a Transform to exist, you cannot unit-test it."),
      h2("root", "Bootstrap"),
      p("A composition root (VContainer or a bootstrap scene) owns lifetimes. DontDestroyOnLoad as architecture produces duplicate services on additive load. Script Execution Order is a patch."),
      h2("data", "Data-driven"),
      p("ScriptableObjects for config and shared data — not a hidden global heap. Addressable prefabs for rooms. Feature flags as data QA can toggle."),
      h2("ugc", "User-generated / downloaded rooms"),
      p("The app ships a lobby and a compatibility window. Rooms are remote content packs with catalogs. Simulation depends on room interfaces, not baked assets. Untrusted content is data, not executable plugins."),
      callout("lead", "Team Lead job", "Enforce boundaries in review. Document where a new feature lives. Protect compile times with asmdefs."),
    ],
  },
  {
    id: "lifecycle",
    title: "Unity lifecycle and execution",
    group: "engineering",
    summary: "Awake through OnDestroy, pause, domain reload, and the subscription bugs a lead bans in review.",
    readMinutes: 10,
    tags: ["Awake", "OnEnable", "coroutines", "pause"],
    related: ["csharp", "networking", "platforms"],
    practiceTopic: "lifecycle",
    suggestedQuestions: [
      "Why pair OnEnable with OnDisable instead of OnDestroy?",
      "What happens if a lambda subscribes to a static event?",
      "Is pause a graphics problem or a networking problem?",
    ],
    blocks: [
      h2("order", "Order"),
      p("Awake (local setup) → OnEnable → Start (talk to others after their Awake) → Update / FixedUpdate / LateUpdate → OnDisable → OnDestroy. Physics uses the fixed timestep."),
      ul([
        "Update: per-frame game/input",
        "FixedUpdate: physics timestep",
        "LateUpdate: camera and post-pose",
      ]),
      h2("pair", "Pairing rule"),
      p("OnEnable/OnDisable must pair because disable happens without destroy. Named methods, not lambdas, on long-lived or static events. Destroyed Unity objects are fake-null."),
      h2("pause", "Mobile pause"),
      p("OnApplicationPause is a networking event: timeout or release occupancy, keep a session token, snapshot on resume. Do not hold a shared tablet lock through a phone call."),
      h2("reload", "Domain reload and Play Mode options"),
      p("Static state survives or disappears depending on Enter Play Mode Options. That can hide bugs the player will show. Additive scenes duplicate bootstraps if services are sloppy."),
      callout("warn", "Review reject", "Lambda on a static lobby event in OnEnable. The destroyed HUD keeps running."),
    ],
  },
  {
    id: "profiling",
    title: "Profiling and optimization",
    group: "engineering",
    summary: "Measurement-first process. CPU vs GPU. Tools. What a lead refuses to call “optimization.”",
    readMinutes: 14,
    tags: ["Profiler", "GPU", "GC", "frame time"],
    related: ["rendering", "ui", "platforms"],
    practiceTopic: "process",
    suggestedQuestions: [
      "Walk the 10-step process for an 18 fps furnished room.",
      "How do I know it is GPU-bound?",
      "What would thermal throttling do to my capture?",
    ],
    blocks: [
      h2("process", "The process"),
      ol([
        "Reproduce the issue",
        "Establish a baseline (frame time p50/p95, not only average fps)",
        "Capture profiler data on a development player of the target device",
        "Classify: CPU, GPU, memory, I/O, network, or loading",
        "Locate the responsible system",
        "Form a hypothesis",
        "Make one controlled change",
        "Measure again",
        "Test on target devices",
        "Check visual and behavioral regressions with art/QA",
      ]),
      h2("cpu-gpu", "CPU-bound vs GPU-bound"),
      p("Compare main-thread CPU, render thread, and GPU time. If CPU waits on GPU, it is GPU-bound. If scripts, physics, animation, UI, or GC eat the frame and GPU is idle, it is CPU-bound. Editor numbers are not device numbers."),
      h2("tools", "Tools"),
      ul([
        "Unity Profiler, Profile Analyzer, Memory Profiler",
        "Frame Debugger, Rendering Debugger",
        "RenderDoc, Android GPU Inspector, Xcode Instruments",
        "Development builds; Deep Profiling to find what, not how expensive",
      ]),
      h2("confuse", "Do not confuse"),
      table(
        ["This", "Is not this"],
        [
          ["Draw-call count", "GPU cost / fill rate"],
          ["Batching", "Instancing"],
          ["Memory usage", "A leak"],
          ["Average fps", "Frame-time consistency / hitches"],
          ["Editor", "Player on mid-range Android"],
        ]
      ),
      h2("lead", "Lead decision"),
      p("Is this a code bug, a content budget, or a quality-tier problem? Who owns the change — engineering or art? Put frame time in the requirements, not in a polish ticket after launch."),
      callout("warn", "Rejected answer", "I would optimize it: pooling, occlusion, ECS, fewer polygons, all at once."),
    ],
  },
  {
    id: "rendering",
    title: "Rendering, URP, and interiors",
    group: "engineering",
    summary: "Batching, SRP Batcher, instancing, overdraw, lights, LODs, shader variants, quality strategy.",
    readMinutes: 13,
    tags: ["URP", "SRP Batcher", "overdraw", "LOD", "lighting"],
    related: ["profiling", "assets", "platforms", "render-pipelines", "vfx-performance"],
    practiceTopic: "batching",
    suggestedQuestions: [
      "Static batching vs GPU instancing vs SRP Batcher?",
      "Why is a glassy meeting room GPU-hot with modest draw calls?",
      "Can occlusion culling help streamed furniture?",
    ],
    blocks: [
      h2("batching", "Batching family"),
      ul([
        "Static batching: combine static same-material meshes; memory cost; breaks if they move",
        "Dynamic batching: limited CPU path; rarely the strategy for a dense 3D room",
        "GPU instancing: many copies of the same mesh and material",
        "SRP Batcher: fewer SetPass calls when shader variants are compatible, even if materials differ slightly",
      ]),
      p("Batching fails on unique materials, some scales, and a lot of transparency. Material property blocks can break the SRP Batcher. Shader variants explode build size and hitch on first use — strip them."),
      h2("overdraw", "Overdraw and fill rate"),
      p("Overdraw is writing the same pixel more than once. Transparent glass, particles, and UI do not occlude. Interiors are often fill-rate bound. Draw-call count will not show it. Use overdraw views and GPU time."),
      h2("culling-lod", "Culling and LOD"),
      p("Frustum culling is off-screen. Occlusion culling is hidden-by-geometry and typically baked — streamed furniture is not in that bake unless you add proxies. LODs reduce vertex and often draw cost. They do not fix stacked transparents in view."),
      h2("lights", "Lights and shadows"),
      p("Realtime lights × shadow cascades are a budget. Mixed lighting and lightmaps cost bake time and memory. Reflection probes and post-processing are not free on mobile. Quality tiers cut cascades and extra lights before they cut readable machines."),
      callout("tip", "URP quality strategy", "Named budgets with owners. Detect RAM/GPU plus a short benchmark. Measure on low and high devices. Artist PCs are not the matrix."),
      p("For a later Technical Artist interview, go deeper in Render pipelines (Unity 6), Particle System, VFX Graph, and Shader Graph. This article stays at the Team Lead bar: batching family, fill rate, quality tiers."),
    ],
  },
  {
    id: "assets",
    title: "Assets, Addressables, and delivery",
    group: "engineering",
    summary: "Resources vs bundles vs Addressables. Unload. Remote rooms. Failure and versioning.",
    readMinutes: 12,
    tags: ["Addressables", "catalog", "CDN", "memory"],
    related: ["profiling", "unity-architecture", "platforms"],
    practiceTopic: "addressables",
    suggestedQuestions: [
      "When can an Addressable actually unload?",
      "Design delivery for hundred-megabyte rooms on Mobile and PC.",
      "Download dies at 80 percent. What happens?",
    ],
    blocks: [
      h2("three", "Resources vs AssetBundles vs Addressables"),
      p("Resources: tiny local set baked into the player. AssetBundles: the packing format. Addressables: catalogs, remote hosting, ref-counting. Large selectable rooms belong on Addressables."),
      h2("unload", "Unload"),
      p("Ref count must hit zero. You still lose if a handle, additive scene, static cache, or instanced material remains. Compare Memory Profiler snapshots: lobby, room A, room B, lobby again. Growth that never drops is a leak or leftover reference. Release is not “GPU memory is gone.”"),
      h2("dup", "Duplicates"),
      p("The same mesh pulled into two groups without a shared bundle appears twice in memory. Fix grouping. Do not put it in Resources to “share.”"),
      h2("delivery", "Remote rooms"),
      ul([
        "Per-room groups plus a shared core (avatars, UI)",
        "Platform variants: mobile LODs/textures vs PC",
        "Lobby + minimum set in the player",
        "Resume, disk checks, retry; failure keeps the lobby usable",
        "Content compatibility window with the client; old apps must not load new schemas",
      ]),
      callout("lead", "CI", "Validate max size, missing refs, shader variants. Telemetry on download success, time-to-enter, failure codes."),
    ],
  },
  {
    id: "animation-physics",
    title: "Animation, physics, and shared interaction",
    group: "engineering",
    summary: "Animator cost for 30 users. Locks not Rigidbodies. Interpolation vs prediction.",
    readMinutes: 10,
    tags: ["Animator", "IK", "physics", "occupancy"],
    related: ["networking", "solid-patterns", "profiling"],
    practiceTopic: "shared-interact",
    suggestedQuestions: [
      "How do I animate 30 avatars on a mid-range phone?",
      "Interpolation vs prediction for a shared tablet?",
      "Two Use requests in the same tick?",
    ],
    blocks: [
      h2("anim-cost", "Animator cost"),
      p("Cost scales with active controllers, layers, and IK. LOD animation, cull off-camera, do not Always Animate 30 characters. Replicate locomotion parameters and gesture ids, not every bone. Root motion on networked avatars is usually a mistake."),
      h2("shared", "Shared machines"),
      p("Request lock → grant → play in-use → release on timeout or disconnect. Kinematic presentation. Do not parent-network-physics a tool to two avatars."),
      h2("interp", "Interpolation vs prediction"),
      p("Interpolation plays remote snapshots slightly in the past. Prediction guesses local movement and reconciles. A shared tablet should not be predicted by two clients."),
      callout(
        "honest",
        "Your gap",
        "You have not shipped a 30-user 3D collaboration room. You have shipped SmartFox, REST, and WebSocket clients. Say that, then design from authority and failure modes. Refuse to bluff bone-replication budgets without a prototype on a mid-range device."
      ),
    ],
  },
  {
    id: "ui",
    title: "UI and UX engineering",
    group: "engineering",
    summary: "Canvas rebuilds, pooling, safe areas, input devices, reactive views.",
    readMinutes: 9,
    tags: ["uGUI", "canvas", "R3", "input"],
    related: ["profiling", "platforms", "csharp"],
    practiceTopic: "canvas",
    suggestedQuestions: [
      "Chat hitch when a message arrives — what do I change?",
      "Where does the view-model live if I already use R3?",
    ],
    blocks: [
      h2("rebuild", "Rebuilds"),
      p("A Canvas rebuilds when geometry or layout changes. A ticking latency label on the same canvas as an inventory grid dirties everything. Split static and dynamic canvases. Disable unused raycast targets. Pool lists. Avoid Best Fit on every Text."),
      h2("input", "Input is architecture"),
      p("Touch versus cursor, safe areas, DPI, controller navigation, localization that must not blow layout every frame. The Input System belongs behind an abstraction so Mobile and PC share rules."),
      h2("r3", "Reactive UI"),
      p("If you already use R3, keep the view-model in plain C#. Occupancy does not live in Button.onClick. Static UIManager polling in Update is the old smell."),
    ],
  },
  {
    id: "networking",
    title: "Multiplayer and online collaboration",
    group: "collaboration",
    summary: "Dedicated server, authority, snapshots, occupancy, reconnect, bandwidth, honesty.",
    readMinutes: 16,
    tags: ["netcode", "authority", "snapshot", "occupancy", "SmartFox"],
    related: ["animation-physics", "assets", "honest-leadership"],
    practiceTopic: "authority",
    suggestedQuestions: [
      "Design a 30-user training room. Start with assumptions.",
      "What must never be client-authoritative?",
      "How do I test 250 ms RTT and 5% loss?",
    ],
    blocks: [
      h2("assumptions", "Start with assumptions"),
      p("30 users, dedicated server, rooms persist layout, content is remote, mobile can suspend, mid-range devices matter. Voice is a separate plane. Version mismatch refuses join."),
      h2("authority", "Authority"),
      p("Server owns shared equipment, occupancy, scores, persistence, join eligibility. Clients own input. Maybe predicted locomotion only. P2P listen-server hosted on the first PC is a poor default for 30 mobile users."),
      h2("sync", "Sync"),
      ul([
        "Tick snapshots + deltas, not every transform at 60 Hz blindly",
        "Interest / relevance so far avatars cost less",
        "Interpolate remotes",
        "Predict local movement if you must; reconcile",
        "Never dual-predict a grab",
      ]),
      h2("reconnect", "Reconnect"),
      p("Session token, full snapshot, then deltas. TCP luck is not a design. Pause must timeout locks."),
      h2("test", "Test"),
      p("Network simulator: 250 ms RTT, 5% loss, two-client grab race, pause-while-locked, reconnect mid-use, version mismatch."),
      h2("security", "Security and cheat"),
      p("Even a training product should validate occupancy and inventory. UGC is untrusted data."),
      callout(
        "honest",
        "Say this out loud",
        "I have not shipped this exact 3D collaboration product. I have shipped clients against SmartFox, REST, and WebSockets. I would choose Unity Netcode or a custom relay only after the authority model is clear."
      ),
      qa("Two Use in one tick?", "Server serializes. One owner. Loser fail-poses and reconciles. No merge of transforms."),
    ],
  },
  {
    id: "platforms",
    title: "Cross-platform deployment",
    group: "collaboration",
    summary: "Android, iOS, Windows. Tiers, thermals, pause, stores, symbols, matrix.",
    readMinutes: 10,
    tags: ["Android", "iOS", "IL2CPP", "quality"],
    related: ["profiling", "rendering", "testing-incidents"],
    practiceTopic: "tiers",
    suggestedQuestions: [
      "How do I pick quality without destroying training value?",
      "What is in the device matrix?",
      "Phone call mid-session — walk the client.",
    ],
    blocks: [
      h2("tiers", "Quality tiers"),
      p("Budgets: resolution scale, shadow cascades, LOD bias, realtime lights, post. Detect RAM, GPU family, short runtime benchmark — not only a marketing name. Cut decoration before readable machines and interaction."),
      h2("lifecycle", "Lifecycle"),
      p("Permissions, store requirements, IL2CPP stripping, crash symbols, thermal throttling after minutes. OnApplicationPause is occupancy + session, not mute."),
      h2("matrix", "Device matrix"),
      p("At least two Android tiers, iOS if you ship it, one Windows box, soak in the heaviest room. The Team Lead owns the matrix with QA. Artist laptops are not coverage."),
      h2("input-ui", "Beyond sliders"),
      p("Safe areas, cursor vs touch, file paths, plugins, conditional compilation only at the edges."),
    ],
  },
  {
    id: "testing-incidents",
    title: "Testing, stability, and incidents",
    group: "delivery",
    summary: "Unit to soak. Crash reporting. Halt, rollback, hotfix. When an incident is actually over.",
    readMinutes: 11,
    tags: ["QA", "Crashlytics", "rollback", "CI"],
    related: ["platforms", "team-leadership", "profiling"],
    practiceTopic: "incident",
    suggestedQuestions: [
      "QA cannot reproduce a mid-range Android crash. What do I do?",
      "Native plugin crash after 10 minutes in one room — divide work.",
    ],
    blocks: [
      h2("tests", "Test types"),
      ul([
        "Unit: domain, occupancy, save schema",
        "Edit Mode / Play Mode: lifecycle, subscribe/unsubscribe",
        "Integration: Addressables failure, catalog mismatch",
        "Performance: room budgets on target devices",
        "Network simulation",
        "Smoke and regression in CI player builds",
      ]),
      h2("incident", "Unreproducible crash"),
      ol([
        "Halt staged rollout",
        "Rate, devices, OS, symbolicated stacks",
        "Rollback vs hotfix by blast radius",
        "Match GPU family, memory pressure, language, room content",
        "Owner, time-boxed status to Product",
        "Then dig",
        "After fix: matrix gap + soak so it is not a hero story next time",
      ]),
      p("Room-specific native crashes are often content + driver, not the C# line in the stack. Divide: you on go/no-go and symbols; junior on isolating the pack; art on unique shaders/VFX; QA on GPU-family soak."),
      callout("lead", "Over when", "Verified on the failing tier, shipped, and the test matrix changed. Slack going quiet is not a close."),
    ],
  },
  {
    id: "requirements",
    title: "Requirements and technical design",
    group: "delivery",
    summary: "Turn slogans into MVP cuts, contracts, ranges, and spikes.",
    readMinutes: 10,
    tags: ["requirements", "estimation", "MVP"],
    related: ["unity-architecture", "networking", "team-leadership"],
    practiceTopic: "req",
    suggestedQuestions: [
      "Product wants virtual rooms in two weeks. What is the cut line?",
      "Where does uncertainty go in an estimate?",
    ],
    blocks: [
      h2("ask", "Questions before a spec exists"),
      ul([
        "Who is the user?",
        "What problem and flow?",
        "Acceptance criteria?",
        "Platforms and device constraints?",
        "Scale?",
        "Persistent? Online? Who owns state?",
        "Failure? Analytics?",
        "What is explicitly out of scope?",
      ]),
      h2("outputs", "What you produce"),
      ul([
        "Assumptions, architecture, component responsibilities",
        "Data flow, API contracts",
        "Risks, edge cases, task breakdown, ranges",
        "Test strategy, rollout, monitoring",
        "Non-goals",
      ]),
      h2("two-weeks", "Two-week slogan vs six-week MVP"),
      p("Cut line example: create from a template, invite by link, join up to N, persist furniture transforms. Out: custom mesh UGC, moderation console, voice, cross-region. Spike occupancy and reconnect on day one. Show the two-week board and the six-week board. Do not silently drop tests."),
      callout("warn", "Estimation", "Do not average a 2-day UI and a 3-week network risk into a fake 1-week number. Uncertainty is a named spike."),
    ],
  },
  {
    id: "team-leadership",
    title: "Team leadership in practice",
    group: "leadership",
    summary: "Delegation, review, conflict, deadlines, incidents, bus factor — without faking a manager title.",
    readMinutes: 11,
    tags: ["mentoring", "review", "conflict", "estimation"],
    related: ["honest-leadership", "testing-incidents", "requirements"],
    practiceTopic: "title-gap",
    suggestedQuestions: [
      "A senior disagrees with my occupancy design.",
      "Unmaintainable code on the revenue path two days before release.",
    ],
    blocks: [
      h2("ic-to-lead", "From implementer to lead"),
      p("Technical leadership is standards, decomposition, and risk. People leadership is coaching, conflict, and unblocking. You will still code; you will not take every ticket. Bus factor: no unique hero path in your head."),
      h2("review", "Code review"),
      p("Examples, not adjectives. Checklist of rejects (events, hot-path alloc, occupancy, Addressables). Teach in the comment. Do not become the bottleneck: standards + samples + pairing."),
      h2("conflict", "Disagreement"),
      p("Steelman their design through reconnect, two-user grab, mobile pause. Time-box a spike if needed. One written decision and a review date. Rank is not the test — you may not even have the title."),
      h2("dates", "Impossible dates"),
      p("Put current frame time and crash risk on the table. Offer cuts. Do not silently accept a death march. Frame time is a requirement."),
      h2("juniors", "Juniors"),
      p("Missed deadlines are a signal: scope, skill, or system. Diagnose, cut, pair. Unmaintainable-but-working on a shared module: protect the release, then coach privately."),
    ],
  },
  {
    id: "ai-workflow",
    title: "AI in the development workflow",
    group: "delivery",
    summary: "Use AI as a research assistant. Humans own correctness, licenses, and secrets.",
    readMinutes: 7,
    tags: ["AI", "review", "security"],
    related: ["team-leadership", "resources"],
    practiceTopic: "ai",
    suggestedQuestions: [
      "How would I let the team use AI without lowering quality?",
      "What must never go in a prompt?",
    ],
    blocks: [
      h2("use", "Good uses"),
      ul(["Research and doc drafts", "Boilerplate and test scaffolds", "Log clustering", "Checklists you then verify against Unity docs"]),
      h2("risk", "Risks"),
      ul([
        "Hallucinated APIs",
        "Leaking proprietary code or player data",
        "License contamination",
        "Overdependence; juniors who cannot explain the diff",
        "Unmaintainable dumps",
      ]),
      h2("policy", "Policy a lead can enforce"),
      ol([
        "No secrets, player PII, or off-limits source in prompts",
        "Every generated diff is reviewed by a human who can explain it",
        "Unknown APIs are false until Unity docs or the package version confirm them",
        "AI does not silently choose occupancy architecture",
      ]),
    ],
  },
  {
    id: "question-bank",
    title: "Question bank",
    group: "interview",
    summary: "Questions you must be able to answer, grouped by seniority. Use the trainer to drill any one.",
    readMinutes: 10,
    tags: ["questions", "bank"],
    related: ["interview-playbook", "cheatsheets"],
    suggestedQuestions: [
      "Pick a Team Lead question at random and help me structure it.",
      "What is the follow-up trap after Addressables?",
    ],
    blocks: [
      h2("background", "Background"),
      ul([
        "Tell me about yourself",
        "Why this simulation product, not casino gameplay?",
        "Why are you ready to lead?",
        "Why you over a formal TL?",
        "Most difficult production issue",
        "Exact contribution vs the team",
      ]),
      h2("unity-c", "Unity and C#"),
      ul([
        "Execution lifecycle",
        "ScriptableObject vs what must not live in MB",
        "Interface vs abstract class; composition vs inheritance",
        "Events and leaks; GC; coroutine vs async",
        "Large project structure; testable Unity; init order",
      ]),
      h2("opt", "Optimization and rendering"),
      ul([
        "CPU vs GPU bound",
        "Memory growth vs leak",
        "Draw calls vs fill rate; when batching fails",
        "Large 3D room on mobile; UI; particles; build size; quality settings",
        "Static vs dynamic vs instancing vs SRP Batcher vs GPU Resident Drawer; occlusion with streamed props; shader variants",
        "Particle System vs VFX Graph; Shader Graph keywords; URP 17 Render Graph",
      ]),
      h2("assets-net", "Assets and multiplayer"),
      ul([
        "Resources vs bundles vs Addressables; unload; duplicates; remote rooms; version mismatch; failed download",
        "30-user sync; server authority; interpolation vs prediction; shared objects; reconnect; bandwidth; loss testing; two users one object",
      ]),
      h2("lead-q", "Leadership"),
      ul([
        "Estimate a feature; divide tasks; mentor; poor-quality code; review; disagreement; technical debt; impossible deadline; incident; coding vs leading; docs; knowledge sharing",
      ]),
    ],
  },
];
